# This is a basic workflow that runs daily
name: Daily run
on:
   schedule:
   - cron: "0 3 * * *"

jobs:
  execute_mail:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run code
        run: python3 src/main.py 0
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          WORLDNEWSAPI_KEY: ${{ secrets.WORLDNEWSAPI_KEY }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
