# This is a basic workflow that runs daily
name: Daily run
on:
  schedule:
    - cron: "0 2 * * *"
  push:
    branches:
      - test/*


jobs:
  execute_mail:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Install dependencies
        run:
          poetry install

      - name: Run script
        run: poetry run python3 src/main.py 0
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          WORLDNEWSAPI_KEY: ${{ secrets.WORLDNEWSAPI_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RECIPIENTS: ${{ github.event_name == 'schedule' && secrets.RECIPIENTS || secrets.RECIPIENTS_TEST }}
