# This is a basic workflow that runs daily
name: Daily run
on:
   schedule:
     - cron: "0 2 * * *"
   push:
      branches:
      - test/*


jobs:
  execute_mail:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set environment for branch
        run: |
          if [[ $GITHUB_REF_NAME == 'master' ]]; then
              echo "RECIPIENTS=${{ secrets.RECIPIENTS }}" >> "$GITHUB_ENV"
          else
              echo "RECIPIENTS=${{ secrets.RECIPIENTS_TEST }}" >> "$GITHUB_ENV"
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run code
        run: poetry run python3 src/main.py 0
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          WORLDNEWSAPI_KEY: ${{ secrets.WORLDNEWSAPI_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}